<?php
/**
 * @File Redesign Login
 * @author Miguel Martínez <miguel01amd@gmail.com>
 * @package BUPA - Redesign V2
 * @info This module contains functions to Custom Login
 * @vertion dev 1.0.0.0
 */

/**
 * Define URLS to admin and sections pages
 * Implements hook_menu().
 * @return array (paths)
 */
function bem_customlogin_menu() {
  $items = [];

  /* Paths */
  $items['bem-login'] = array(
    'title'            => 'Login',
    'description'      => 'BEM - LOGIN',
    'page callback'    => 'bem_customlogin_page_empty',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * @info Define empty page
 * @return (string)
*/
function bem_customlogin_page_empty() {
  return '';
}

/*
 * Implements hook_block_info().
 * Declare blocks to home
 * @blocks
 *   bem_login
 */
function bem_customlogin_block_info() {
  $blocks = [];
  $blocks['bem_login'] = array(
    'info'       => 'Redesign | Login',
    'status'     => TRUE,
    'region'     => 'content_bupa',
    'cache'      => DRUPAL_NO_CACHE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages'      => 'bem-login',
    'weight'     => 1,
  );

  return $blocks;
}

/*
 * Implements hook_block_view().
 * Callback to block info
 */
function bem_customlogin_block_view($delta = '') {
  $block = [];

  switch ($delta) {
    case 'bem_login':
      if( !user_is_logged_in() ){
        $content = [
            'info' => bem_customlogin_getinfo(),
            'form' => drupal_get_form("bem_customlogin_form_login"),
            'theme_path' => drupal_get_path('theme', 'bupatheme'),
            'login_inicio_sesion' => variable_get('login_inicio_sesion',''),
            'login_subtitulo' => variable_get('login_subtitulo',''),
            'login_descr' => variable_get('login_descr','')['value'],
            'msn_titulo' => variable_get('msn_titulo',''),
            'msn_subtitulo' => variable_get('msn_subtitulo',''),
            'msn_descr' => variable_get('msn_descr','')['value'],
        ];

        drupal_add_js(drupal_get_path('theme', 'bupatheme') . '/js/login-user.js', array('scope' => 'footer', 'weight' => 10));
        $block['content'] = theme('bem_login', array('content' => $content));
      }
      else{
        global $base_url;
        drupal_goto($base_url . '/user');
      } // endif
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 * @return array
 * @see templates
 */
function bem_customlogin_theme() {
  $theme = [];
  $theme['form_customlogin_login'] = [ 'render element' => 'form', 'template' => 'templates/form-login' ];
  $theme['form_customlogin_pass'] = [ 'render element' => 'form', 'template' => 'templates/form-pass' ];
  $theme['form_customreset_pass'] = [ 'render element' => 'form', 'template' => 'templates/form-reset' ];
  $theme['bem_login']             = [ 'template' => 'templates/block-login' ];

  return $theme;
}

/**
 * Get info to template
 * @return array ($info)
 * @see bem_customlogin_block_view
 */
function bem_customlogin_getinfo()
{
    $info = [];

    $qry = db_select('node', 'n');
    $qry->leftJoin('field_data_field_titulo_renglon1', 't1', 't1.entity_id = n.nid');
    $qry->leftJoin('field_data_field_titulo_renglon2', 't2', 't2.entity_id = n.nid');
    $qry->leftJoin('field_data_field_subtitulo', 'subt', 'subt.entity_id = n.nid');
    $qry->leftJoin('field_data_field_introduccion', 'intro', 'intro.entity_id = n.nid');
    $qry->leftJoin('field_data_field_imagen_de_fondo', 'img', 'img.entity_id = n.nid');
    $qry->leftJoin('field_data_field_register', 'link', 'link.entity_id = n.nid');
    $qry->leftJoin('field_data_field_url_noticia', 'video', 'video.entity_id = n.nid');
    $qry->leftJoin('field_data_field_icon_svg', 'svg', 'svg.entity_id = n.nid');
    $qry->leftJoin('field_data_field_login_video_visible‎', 'vvd', 'vvd.entity_id = n.nid');
    $qry->condition('n.type', 'login');
    $qry->condition('n.status', 1);
    $qry->fields('n', ['nid', 'title'])
        ->fields('t1', ['field_titulo_renglon1_value'])
        ->fields('t2', ['field_titulo_renglon2_value'])
        ->fields('subt', ['field_subtitulo_value'])
        ->fields('intro', ['field_introduccion_value'])
        ->fields('img', ['field_imagen_de_fondo_fid'])
        ->fields('link', ['field_register_url', 'field_register_title'])
        ->fields('video', ['field_url_noticia_value'])
        ->fields('svg', ['field_icon_svg_fid'])
        ->fields('vvd', ['field_login_video_visible_value']);
    $qry->range(0, 1);
    $qry->orderBy('n.changed', 'ASC');

    $results = $qry->execute()->fetchAll();

    if (!empty($results)) {
        foreach ($results as $value) {
            $info = [
                'tit1' => $value->field_titulo_renglon1_value,
                'tit2' => $value->field_titulo_renglon2_value,
                'subt' => $value->field_subtitulo_value,
                'intro' => $value->field_introduccion_value,
                'img' => bem_common_getimg($value->field_imagen_de_fondo_fid),
                'url_url' => $value->field_register_url,
                'url_name' => $value->field_register_title,
                'video' => $value->field_url_noticia_value,
                'is_video' => $value->field_login_video_visible_value,
                'svg' => bem_common_getimg($value->field_icon_svg_fid),
            ];
        }// endoreach
    }// endif

    return $info;
}

/**
 * Definition to login form
 * @return array to fomr ($form).
 */
function bem_customlogin_form_login(){

  $form = [];

  $form['bem_customlogin_user_login'] = array(
    '#type'           => 'textfield',
    '#title_display'  => 'before',
    '#default_value'  => '',
    '#attributes'     => array( 'class' => array('form-control'), 'id' => 'user', 'placeholder' => 'Nombre de usuario'),
    '#theme_wrappers' => array()
  );

  $form['bem_customlogin_password_login'] = array(
    '#type'           => 'password',
    '#title_display'  => 'before',
    '#default_value'  => '',
    '#attributes'     => array(
      'class'        => array('form-control pr-5'),
      'autocomplete' => 'off',
      'id'           => 'password',
      'data-type'    => 'password',
      'placeholder'  => 'Contraseña',
    ),
    '#theme_wrappers' => array()
  );

  $form['bem_customlogin_redirect_private_nodeid'] = array(
    '#type'   => 'hidden',
    '#value'  => $_GET["redirectProtectedNodeId"]
  );

  $form['submit'] = array(
      '#type'       => 'submit' ,
      '#value'      => 'Iniciar Sesión',
      '#attributes' => array('class' => array('btn btn-primary btn-orange')),
      '#validate'   => array('bem_customlogin_form_login_validate'),
      '#submit'     => array('bem_customlogin_form_login_submit')
  );

  $form['#theme']          = 'form_customlogin_login';
  $form['#theme_wrappers'] = array('form');
  $form['#attributes'] = array('class' => 'data', 'ng-controller' => 'passInput');

  return $form;
}

/**
 * Validate the form params on
 * @see bem_customlogin_form_login
 */
function bem_customlogin_form_login_validate($form, &$form_state){
  if (empty($form_state['values']['bem_customlogin_user_login'])) {
    form_set_error('bem_customlogin_user_login', 'Ingrese un usuario válido');
    drupal_set_message(t('Ingrese un usuario válido.'), 'error');
  }// endif

  if (empty($form_state['values']['bem_customlogin_password_login'])) {
    form_set_error('bem_customlogin_password_login', 'Ingrese una contraseña' );
    drupal_set_message(t('Ingrese una contraseña.'), 'error');
  }// endif
}

/**
 * Login on site
 * @see bem_customlogin_form_login
 * @param (array) $form
 *        (array) $form_state
 * @return array.
 */
function bem_customlogin_form_login_submit($form,&$form_state){
  if(!empty($form_state["values"]["bem_customlogin_redirect_private_nodeid"])){
    $node = node_load($form_state["values"]["bem_customlogin_redirect_private_nodeid"]);
    $_SESSION['redirect_private_nodeid'] = $node->field_bbn_documentos['und'][0]['field_bbn_ano_1']['und'][0]['url'];
  }
  // Load entity user by email form
  $user_load = user_load_by_name($form_state["values"]["bem_customlogin_user_login"]);
  if (!$user_load){
      $user_load = user_load_by_mail($form_state["values"]["bem_customlogin_user_login"]);
  }
  if( isset($user_load->name) ) {
    if($uid = user_authenticate($user_load->name,$form_state["values"]["bem_customlogin_password_login"])){
      global $base_url;
      global $user;
      $user                   = $user_load;
      $login_array            = ['name' => $user->name ];
      user_login_finalize($login_array);
      /*
      if (isset($_SESSION['redirect'])) {
        $url_r = $_SESSION['redirect'];
        unset($_SESSION['redirect']);
        $form_state['redirect'] = $url_r;
        drupal_goto($url_r);
      } else{
        drupal_goto('<front>');
      }*/
    }// endif
    else{
      form_set_error('error_login', 'Contraseña incorrecta.' );
      drupal_set_message(t('Ingrese una contraseña válida.'), 'error');
    }
  }// endif
  else{
    form_set_error('error_login', 'Usuario incorrecto. ' );
    drupal_set_message(t('No se encuentra usuario con ese nombre.'), 'error');
  }
  return;
}

/**
 * Use preprocess_page() hook.
 * Function to redirect login custom
 */
function bem_customlogin_preprocess_page(&$variables) {
  // Load the URL Request
  $path = request_path();
  $redirectProtectedNodeId = $_GET["redirectProtectedNodeId"];
  if ($redirectProtectedNodeId != "") {
    $redirectProtectedNodeId = "?redirectProtectedNodeId=$redirectProtectedNodeId";
  }
  // Redirect to new URL
  if ( !empty($path) ) {
    $extra = 'bem-login';
    switch ($path) {
      case 'login':
      case 'user/login':
        $host = $_SERVER['HTTP_HOST'];
        header("Location: https://$host/$extra$redirectProtectedNodeId");
        break;

    } // endswitch
  }// endif

}

/**
 * @param $variables
 */
function bem_customlogin_preprocess_user_pass(&$variables) {

    $variables['intro'] = t("intro");
    $variables['form']['form_id']['#attributes']["class"][0] = "data";
    $variables['form']['name']['#title_display'] = 'none';
    $variables['form']['name']['#attributes']["class"][0] = "form-control invalid";
    $variables['form']['name']['#attributes']["placeholder"] = t("Introduce tu correo electrónico*");

    $variables['form']['actions']['submit']['#attributes']["class"][0] = "btn btn-primary btn-orange";
    $variables['form']['actions']['submit']['#value'] = t("Continuar");
}
